### ISSUE TITLE
Class 'MyApp\Socket' not found

### ISSUE THREAD

**Issue by SteMMo33** [themarcusbattle/ratchet-php-websocket-server-starter#1]
Hi, very nide article!
I downloaded the sample and the Ratchet lib.
Now if I run 'php app.php' I receive the error:

PHP Fatal error:  Class 'Ratchet\Server\IoServer' not found in /home/amtek/msgserver/ratchet-php-websocket-server-starter/app.php on line 10

This is the fie structure:

root@amtekboard:/home/amtek/msgserver/ratchet-php-websocket-server-starter# ls -l
total 32
-rw-r--r-- 1 root root  296 Nov 18 12:00 README.md
drwxr-xr-x 7 root root 4096 Nov 18 12:06 Ratchet
drwxr-xr-x 5 root root 4096 Nov 18 12:03 Ratchet_git
drwxr-xr-x 2 root root 4096 Nov 18 12:00 app
-rw-r--r-- 1 root root   48 Nov 18 12:00 app.js
-rw-r--r-- 1 root root  317 Nov 18 12:02 app.php
-rw-r--r-- 1 root root  142 Nov 18 12:00 composer.json
-rw-r--r-- 1 root root  681 Nov 18 12:00 index.html

Is it correct?

**Comment by SteMMo33** [comment]
Sorry, I'm very new about php application and the use of composer tool.
I run the 'composer install' cmd and the error got away.
But now i have:
PHP Fatal error:  Class 'MyApp\Socket' not found in /home/amtek/msgserver/ratchet-php-websocket-server-starter/app.php on line 13

**Comment by angelohenq** [comment]
Same error here

**Comment by Tiebe** [comment]
Try `composer dump-autoload --classmap-authoritative`

**Comment by cochee83** [comment]
Loading classes from filenames is case-sensitive in Unix/Linux environment.  Rename the file socket.php to Socket.php.  The author probably implemented in Windows where filenames are case insensitive.

**Comment by MassaM-SDC** [comment]
I use **Laragon** in **Windows10/64bit** and when i run in terminal with:

`php app.php `

I get this error:


`Fatal error: Uncaught RuntimeException: Failed to listen on "tcp://0.0.0.0:8080": An attempt was made to access a socket in a way forbidden by its access permissions.
 in C:\laragon\www\websocketchat\vendor\react\socket\src\TcpServer.php:165`

`Stack trace:`

`#0 C:\laragon\www\websocketchat\vendor\react\socket\src\Server.php(36): React\Socket\TcpServer->__construct('tcp://0.0.0.0:8...', Object(React\EventLoop\StreamSelectLoop), Array)`

`#1 C:\laragon\www\websocketchat\vendor\cboden\ratchet\src\Ratchet\Server\IoServer.php(59): React\Socket\Server->__construct('0.0.0.0:8080', Object(React\EventLoop\StreamSelectLoop))`

`#2 C:\laragon\www\websocketchat\app.php(16): Ratchet\Server\IoServer::factory(Object(Ratchet\Http\HttpServer), 8080)
#3 {main}`
`thrown in C:\laragon\www\websocketchat\vendor\react\socket\src\TcpServer.php on line 165`
  
Any help to troubleshoot this to work is appreciated.
